module.exports = Object.freeze({
    STATUS_OK: 'OK',
    UPDATE_LIST: 'UPDATE_LIST',
    DISPLAY_INPUT_FIELD: 'DISPLAY_INPUT_FIELD',
    HOME_PAGE_LOADED: 'HOME_PAGE_LOADED',

    ADD: 'add',
    REMOVE: 'remove',
    UPDATE: 'update',
    
    GET_TODOS: 'GET_TODOS',
    ADD_TODO: 'ADD_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    COMPLETE_TODO: 'COMPLETE_TODO',
    DELETE_TODO: 'DELETE_TODO',

    CREATE_USER: 'CREATE_USER',
    REMOVE_USER: 'REMOVE_USER',
    GET_USERS: 'GET_USERS',
})